[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
remappings = [
    "forge-std/=dependencies/forge-std-1.9.6/src/",
    "@uniswap/v4-core/=dependencies/v4-periphery-1.0.0/lib/v4-core/",
    "@uniswap/v4-periphery/=dependencies/v4-periphery-1.0.0/",
]

[fmt]
line_length = 80
multiline_func_header = "params_first"

[lint]
exclude_lints = ["mixed-case-function"]

[soldeer]
remappings_generate = false
recursive_deps = true

[dependencies]
forge-std = { version = "1.9.6", git = "https://github.com/foundry-rs/forge-std.git", tag = "v1.9.6" }
v4-periphery = { version = "1.0.0", git = "https://github.com/Uniswap/v4-periphery.git", branch = "main" }
